version: '3.8'

services:
  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    ports:
      - "5436:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data


volumes:
  order_db_data:
