spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5436/order_db
    username: order_user
    password: order_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG